name: Publish Kami.Utils

on:
  push:
    branches: master
    paths:
      - .github/workflows/nuget.yml
      - Kami.Utils/**

env:
  VERSION: 0.0.0
  PROJECT_NAME: Kami.Utils
  PROJECT_PATH: Kami.Utils/Kami.Utils.csproj
  NUGET_SOURCE: "https://nuget.danteiru.space"

jobs:
  nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.2
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'
    - name: Build
      run: "dotnet build $PROJECT_PATH -c Release"
    - name: Pack
      run: "dotnet pack $PROJECT_PATH -o ./ -p:Version=$VERSION --no-build -c Release"
    - name: Push
      run: "dotnet nuget push ./$PROJECT_NAME.$VERSION.nupkg -s $NUGET_SOURCE -k ${{ secrets.NUGET_API_KEY }}"
