name: Publish Kami.Utils

on:
  push:
    branches: master
    paths:
      - Kami.Utils/**
  workflow_dispatch:

env:
  PROJECT_NAME: Kami.Utils
  PROJECT_PATH: Kami.Utils/Kami.Utils.csproj

jobs:
  tag:
    name: Tag
    uses: Kamikoto-sama/DotNetUtils/.github/workflows/tag.yml@master
    permissions:
      contents: write

  nuget:
    name: Publish nuget
    runs-on: ubuntu-latest
    needs: tag
    env:
      VERSION: "${{ needs.tag.outputs.semVer }}"
    steps:
    - uses: actions/checkout@v3.5.2
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'
    - name: Build
      run: "dotnet build $PROJECT_PATH -c Release"
    - name: Pack
      run: "dotnet pack $PROJECT_PATH -o ./ -p:Version=$VERSION --no-build -c Release"
    - name: Push
      run: "dotnet nuget push ./$PROJECT_NAME.$VERSION.nupkg -s ${{ secrets.NUGET_SOURCE }} -k ${{ secrets.NUGET_API_KEY }}"
